### ISSUE TITLE
raise.com paths exposed in .emacs.d/places

### ISSUE THREAD

**Issue by redsquirrel** [pedroassumpcao/dotfiles#1]
Hi Pedro! I hope you're well. Hey would you mind removing all of the raise.com references in this file?

https://github.com/pedroassumpcao/dotfiles/blob/master/.emacs.d/places

**Comment by pedroassumpcao** [comment]
Hey Dave, no problems, I will remove them. Would you mind tell me how/why did you get to this files and my repo?

**Comment by redsquirrel** [comment]
Thanks Pedro!

This file was found via an external security audit.

**Comment by pedroassumpcao** [comment]
Done.
